---
deployment:
  tasks:
    - export DEPLOYPATH=/home/antixlzd/polaroid-ecommerce.antierfamily.com/
    - source /home/antixlzd/nodevenv/polaroid-ecommerce.antierfamily.com/14/bin/activate
    - npm install